"""Adding news table

Revision ID: e13c5626ace0
Revises: 
Create Date: 2024-06-02 23:12:07.921227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13c5626ace0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('reporter', sa.String(), nullable=True),
    sa.Column('news_datetime', sa.String(), nullable=True),
    sa.Column('news_content', sa.String(), nullable=True),
    sa.Column('news_link', sa.String(), nullable=True),
    sa.Column('news_image', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
